version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db/lynxdb
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lynxdb
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
